-- 序列
-- cache 策略同 bank: 高频写入(流水/计划/日志)给 cache，主数据 nocache 保连续便于排查
-- 主数据起始值拉开数量级，dba 看 id 量级即知归属

CREATE SEQUENCE seq_category_id    START WITH 100    INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_item_id        START WITH 10000  INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_bom_id         START WITH 1000   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_bom_line_id    START WITH 1      INCREMENT BY 1 CACHE 50  NOCYCLE;
CREATE SEQUENCE seq_warehouse_id   START WITH 10     INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_location_id    START WITH 1000   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_supplier_id    START WITH 5000   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_customer_id    START WITH 6000   INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_lot_id         START WITH 700000 INCREMENT BY 1 CACHE 100 NOCYCLE;
CREATE SEQUENCE seq_inv_txn_id     START WITH 800000 INCREMENT BY 1 CACHE 100 NOCYCLE;
CREATE SEQUENCE seq_po_id          START WITH 200000 INCREMENT BY 1 CACHE 20  NOCYCLE;
CREATE SEQUENCE seq_po_line_id     START WITH 1      INCREMENT BY 1 CACHE 50  NOCYCLE;
CREATE SEQUENCE seq_so_id          START WITH 300000 INCREMENT BY 1 CACHE 20  NOCYCLE;
CREATE SEQUENCE seq_so_line_id     START WITH 1      INCREMENT BY 1 CACHE 50  NOCYCLE;
CREATE SEQUENCE seq_prod_id        START WITH 400000 INCREMENT BY 1 CACHE 20  NOCYCLE;
CREATE SEQUENCE seq_mrp_run_id     START WITH 1      INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_mrp_plan_id    START WITH 1      INCREMENT BY 1 CACHE 200 NOCYCLE;
CREATE SEQUENCE seq_price_list_id  START WITH 1      INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_price_rule_id  START WITH 1      INCREMENT BY 1 CACHE 50  NOCYCLE;
CREATE SEQUENCE seq_forecast_id    START WITH 1      INCREMENT BY 1 CACHE 200 NOCYCLE;
CREATE SEQUENCE seq_error_log_id   START WITH 1      INCREMENT BY 1 CACHE 50  NOCYCLE;
CREATE SEQUENCE seq_audit_log_id   START WITH 1      INCREMENT BY 1 CACHE 50  NOCYCLE;
